run:
  tests: false

linters:
  enable-all: true
  disable:
    - cyclop              # (*) should not really be disabled; enable this linter once violations are resolved
    - exhaustive          # impractical
    - exhaustruct         # impractical
    - funlen              # too subjective
    - nonamedreturns      # named returns are required to handle errors from deferred functions
    - tagliatelle         # (*) should not really be disabled; enable this linter once violations are resolved
    - varnamelen          # disallows short variable names even if they are appropriate
    - wsl                 # too aggressive

    # deprecated linters:
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - varcheck

    # linters disabled because of generics:
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign

linters-settings:
  dupword:
    keywords:
      - 'a'
      - 'and'
      - 'the'
  lll:
    tab-width: 4

issues:
  exclude-rules:
    # exclude lines with comments from lll
    - linters:
        - lll
      source: "//"

    # exclude lines with long struct tags, which cannot be split over multiple lines, from lll
    - linters:
        - lll
      source: "`(.*)`"

    # clash with swagger:parameters annotations
    - path: api/handle_v3_pe_task_*
      linters:
        - stylecheck
        - revive

    # this package contains quite a few print statements, global variables, and init functions
    - path: cmd/
      linters:
        - forbidigo
        - gochecknoglobals
        - gochecknoinits

    # this file contains the global config variable
    - path: config/config.go
      linters:
        - gochecknoglobals

    # this file contains the global db variable
    - path: db/resolver/db_helpers.go
      linters:
        - gochecknoglobals

    # excluded due to https://github.com/go-swagger/go-swagger/issues/2759
    - path: docs/docs.go
      linters:
        - gofmt
        - gofumpt
        - goimports

    # this file is only used in testing, so these linters are not important here
    - path: testutils/helpers.go
      linters:
        - gosec
        - ireturn
        - noctx
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
