name: Check

on:
  pull_request:
  workflow_dispatch:

jobs:
  update-swagger-specification:
    runs-on: ubuntu-latest
    name: Update Swagger Specification
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SCARP_DEPLOY_KEY }} # required for CI checks to be triggered after an auto-commit
      - name: Set up Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Install go-swagger
        run: go install github.com/go-swagger/go-swagger/cmd/swagger@latest
      - name: Generate Swagger specification
        run: make generate-swagger
      - name: Commit changes, if necessary
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-update Swagger specification
  prettify-hasura-metadata:
    runs-on: ubuntu-latest
    name: Prettify Hasura Metadata
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SCARP_DEPLOY_KEY }} # required for CI checks to be triggered after an auto-commit
      - name: Prettify Hasura metadata
        run: make prettify-hasura-metadata
      - name: Commit changes, if necessary
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Auto-update Hasura metadata
