name: Prune
on:
  workflow_dispatch:

jobs:
  prune1:
    runs-on: [self-hosted, prod-1]
    steps:
    - name: Prune
      shell: bash
      run: docker system prune -f --volumes
  prune2:
    runs-on: [self-hosted, prod-2]
    steps:
    - name: Prune
      shell: bash
      run: docker system prune -f --volumes
  prune3:
    runs-on: [self-hosted, prod-3]
    steps:
    - name: Prune
      shell: bash
      run: docker system prune -f --volumes
  prune4:
    runs-on: [self-hosted, prod-4]
    steps:
    - name: Prune
      shell: bash
      run: docker system prune -f --volumes
