name: Security

on:
  pull_request:
  workflow_dispatch:

jobs:
  snyk-scan:
    name: Snyk Scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Check for vulnerabilities
        uses: snyk/actions/golang@master
        with:
          args: --all-projects --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_COMPLY_KEY }}
      - name: Update dashboard
        uses: snyk/actions/golang@master
        with:
          command: monitor
          args: --org=puppet-comply --project-name=${{ github.repository }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_COMPLY_KEY }}
